accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

]

microblogging/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from posts import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('', post_views.post_list, name="home"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name="list"),
    path('create/', views.post_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name="detail"),
    path('posts/delete_post/', views.delete_post, name="delete_post"),


]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


def __str__(self):
    return self.title


def snippet(self):
    return self.body[:70] + '...'

posts/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'thumb',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.views.generic.edit import DeleteView


def signup_view(request):
    if request.method == 'POST':
       form = UserCreationForm(request.POST) 
       if form.is_valid():
           user = form.save()
           login(request, user)
           return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:           
                return redirect(request.POST.get('next'))
            else:    
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('posts:list')

microblogging/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html')

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms


def post_list(request):
    posts = Post.objects.all().order_by('date')
    return render(request, 'posts/post_list.html', {'posts': posts})


def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_detail.html', {'post': post})


@login_required(login_url="/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_create.html', {'form': form})

def delete_post(request, post_list):
    post = Post.objects.get(pk=post_list)
    post.delete()
    posts = Post.objects.filter(user=request.user)
    return render(request, 'post/delete_post.html', {'posts': posts})

accounts/templates/accounts/delete_post.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Delete</h1>
 <form action="{% url 'posts:delete_post' %}" method="post" style="display: inline;">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <button type="submit" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-trash"></span>
        </button>
    </form>
    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

 {% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
         <input type="hideen" name="next" value="{{ request.GET.next}}">
         {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

 {% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="create-post">
    <h2>Create a New Post</h2>
    <form class="site-form" action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="post-detail">
    <div class="post">
        <img src="{{ post.thumb.url }}" />
        <h2>{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <p>{{ post.date }}</p>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base_layout.html' %}
{% block content%}
<h1>Posts List</h1>
<div class="post">
    {% for post in posts %}
    <div class="post">
        <h2><a href="{% url 'posts:detail' slug=post.slug %}">{{ post.title }}</a></h2>
        <p>{{ post.snippet }}</p>
        <p>{{ post.date }}</p>
        <p class="author">added by {{ post.author.username}}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Microlly.net</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="microblogging" </a> </h1> <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'posts:create' %}" class="highlight">New Post</a></li>
                    <li><a href="{% url 'posts:delete_post' %}" class="highlight">Delete</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>

                    {% endif %}

                    
                </ul>
                </nav>
    </header>
    <div class="wrapper">
        {% block content %}


        {% endblock %}
    </div>
</body>

</html>

templates/homepage.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Accueil</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <h1>Ceci est ma page d'accueil</h1>
    <p>Bienvenue sur le site de Microlly</p>
    {% block content %}

    {% endblock %}
</body>

</html>